In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("qoute_dataset.csv")

In [4]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [5]:
df.shape

(3038, 2)

In [6]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [7]:
quotes = quotes.str.lower()
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices, harry, that show what we t...
2    “there are only two ways to live your life. on...
3    “the person, be it gentleman or lady, who has ...
4    “imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [8]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [9]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [10]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [11]:
vocab_size = 10000

tokinizer = Tokenizer(num_words=vocab_size)
tokinizer.fit_on_texts(quotes)

In [12]:
word_index = tokinizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [13]:
sequence  = tokinizer.texts_to_sequences(quotes)

In [14]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [15]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [16]:
X = []
y = []

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [17]:
len(X)

85271

In [18]:
len(y)

85271

In [19]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [20]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [21]:
y = np.array(y)

In [22]:
X_padded.shape

(85271, 745)

In [23]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [24]:
y.shape

(85271,)

In [25]:
y_one_hot.shape

(85271, 10000)

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM, Dense

In [27]:
embedding_dim = 50
rnn_units = 128

In [28]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [29]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [30]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [32]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [33]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
epoch= 100
batch_size = 128
hist_lstm = lstm_model.fit(X_padded, y_one_hot, epochs=epoch, batch_size=batch_size, validation_split=0.1)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 60ms/step - accuracy: 0.0389 - loss: 6.7636 - val_accuracy: 0.0446 - val_loss: 6.6803
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.0569 - loss: 6.3281 - val_accuracy: 0.0606 - val_loss: 6.5870
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.0745 - loss: 6.0892 - val_accuracy: 0.0818 - val_loss: 6.4840
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 57ms/step - accuracy: 0.0942 - loss: 5.8672 - val_accuracy: 0.0936 - val_loss: 6.4505
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 60ms/step - accuracy: 0.1061 - loss: 5.6880 - val_accuracy: 0.0984 - val_loss: 6.4483
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.1155 - loss: 5.5237 - val_accuracy: 0.1032 - val_loss: 6.4443
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.1263 - loss: 5.3627 - val_accuracy: 0.1047 - val_loss: 6.4635
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1344 - loss: 5.2125 - val_accuracy: 0.1066 - val_loss: 6.4871
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.1415 - loss: 5.0716 - val_accuracy: 0.1085 - val_loss: 6.5228
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.1478 - loss: 4.9376 - val_accuracy: 0.1148 - val_loss: 6.5733
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1560 - loss: 4.8076 - val_accuracy: 0.1154 - val_loss: 6.6201
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1638 - loss: 4.6799 - val_accuracy: 0.1155 - val_loss: 6.6814
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1715 - loss: 4.5558 - val_accuracy: 0.1105 - val_loss: 6.7295
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.1806 - loss: 4.4341 - val_accuracy: 0.1160 - val_loss: 6.7948
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.1918 - loss: 4.3144 - val_accuracy: 0.1162 - val_loss: 6.8632
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.2035 - loss: 4.1996 - val_accuracy: 0.1169 - val_loss: 6.9296
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.2176 - loss: 4.0904 - val_accuracy: 0.1167 - val_loss: 7.0132
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.2308 - loss: 3.9822 - val_accuracy: 0.1163 - val_loss: 7.0952
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.2436 - loss: 3.8809 - val_accuracy: 0.1175 - val_loss: 7.1719
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.2590 - loss: 3.7854 - val_accuracy: 0.1127 - val_loss: 7.2494
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.2722 - loss: 3.6967 - val_accuracy: 0.1122 - val_loss: 7.3340
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.2835 - loss: 3.6132 - val_accuracy: 0.1130 - val_loss: 7.3945
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.2978 - loss: 3.5342 - val_accuracy: 0.1120 - val_loss: 7.4847
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.3082 - loss: 3.4588 - val_accuracy: 0.1082 - val_loss: 7.5571
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.3198 - loss: 3.3882 - val_accuracy: 0.1087 - val_loss: 7.6248
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.3305 - loss: 3.3209 - val_accuracy: 0.1088 - val_loss: 7.6966
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.3407 - loss: 3.2560 - val_accuracy: 0.1093 - val_loss: 7.7734
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.3522 - loss: 3.1943 - val_accuracy: 0.1076 - val_loss: 7.8536
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.3612 - loss: 3.1345 - val_accuracy: 0.1085 - val_loss: 7.9225
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.3699 - loss: 3.0767 - val_accuracy: 0.1060 - val_loss: 8.0011
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.3788 - loss: 3.0224 - val_accuracy: 0.1057 - val_loss: 8.0622
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.3877 - loss: 2.9671 - val_accuracy: 0.1046 - val_loss: 8.1308
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.3971 - loss: 2.9153 - val_accuracy: 0.1040 - val_loss: 8.2028
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.4061 - loss: 2.8652 - val_accuracy: 0.1015 - val_loss: 8.2544
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.4147 - loss: 2.8154 - val_accuracy: 0.1027 - val_loss: 8.3112
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.4211 - loss: 2.7686 - val_accuracy: 0.1028 - val_loss: 8.3844
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 59ms/step - accuracy: 0.4297 - loss: 2.7223 - val_accuracy: 0.1004 - val_loss: 8.4368
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.4392 - loss: 2.6758 - val_accuracy: 0.0976 - val_loss: 8.5014
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.4459 - loss: 2.6331 - val_accuracy: 0.1004 - val_loss: 8.5630
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.4538 - loss: 2.5900 - val_accuracy: 0.1008 - val_loss: 8.6278
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.4611 - loss: 2.5481 - val_accuracy: 0.0993 - val_loss: 8.6905
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.4688 - loss: 2.5085 - val_accuracy: 0.1001 - val_loss: 8.7603
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 59ms/step - accuracy: 0.4756 - loss: 2.4683 - val_accuracy: 0.0980 - val_loss: 8.8288
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.4823 - loss: 2.4316 - val_accuracy: 0.0979 - val_loss: 8.8876
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.4888 - loss: 2.3929 - val_accuracy: 0.0952 - val_loss: 8.9295
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.4963 - loss: 2.3554 - val_accuracy: 0.0971 - val_loss: 9.0103
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.5029 - loss: 2.3207 - val_accuracy: 0.0957 - val_loss: 9.0578
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.5095 - loss: 2.2868 - val_accuracy: 0.0978 - val_loss: 9.1189
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.5159 - loss: 2.2521 - val_accuracy: 0.0971 - val_loss: 9.1679
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.5224 - loss: 2.2190 - val_accuracy: 0.0970 - val_loss: 9.2304
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.5281 - loss: 2.1873 - val_accuracy: 0.0957 - val_loss: 9.2822
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.5350 - loss: 2.1549 - val_accuracy: 0.0937 - val_loss: 9.3327
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.5411 - loss: 2.1251 - val_accuracy: 0.0940 - val_loss: 9.3982
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.5467 - loss: 2.0943 - val_accuracy: 0.0938 - val_loss: 9.4442
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.5519 - loss: 2.0652 - val_accuracy: 0.0966 - val_loss: 9.5003
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.5582 - loss: 2.0361 - val_accuracy: 0.0916 - val_loss: 9.5591
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.5651 - loss: 2.0080 - val_accuracy: 0.0932 - val_loss: 9.6074
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.5699 - loss: 1.9806 - val_accuracy: 0.0923 - val_loss: 9.6647
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.5737 - loss: 1.9541 - val_accuracy: 0.0891 - val_loss: 9.7316
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.5795 - loss: 1.9281 - val_accuracy: 0.0929 - val_loss: 9.7892
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.5863 - loss: 1.9021 - val_accuracy: 0.0896 - val_loss: 9.8291
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.5904 - loss: 1.8771 - val_accuracy: 0.0902 - val_loss: 9.8762
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.5957 - loss: 1.8518 - val_accuracy: 0.0904 - val_loss: 9.9468
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6014 - loss: 1.8268 - val_accuracy: 0.0888 - val_loss: 9.9766
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 60ms/step - accuracy: 0.6045 - loss: 1.8053 - val_accuracy: 0.0870 - val_loss: 10.0417
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6103 - loss: 1.7818 - val_accuracy: 0.0886 - val_loss: 10.0887
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6144 - loss: 1.7576 - val_accuracy: 0.0874 - val_loss: 10.1292
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6191 - loss: 1.7373 - val_accuracy: 0.0878 - val_loss: 10.1842
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6242 - loss: 1.7149 - val_accuracy: 0.0892 - val_loss: 10.2444
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6290 - loss: 1.6939 - val_accuracy: 0.0874 - val_loss: 10.3048
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6327 - loss: 1.6723 - val_accuracy: 0.0865 - val_loss: 10.3513
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6367 - loss: 1.6516 - val_accuracy: 0.0886 - val_loss: 10.3945
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6418 - loss: 1.6305 - val_accuracy: 0.0864 - val_loss: 10.4549
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6462 - loss: 1.6126 - val_accuracy: 0.0876 - val_loss: 10.4984
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6502 - loss: 1.5927 - val_accuracy: 0.0851 - val_loss: 10.5462
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6547 - loss: 1.5743 - val_accuracy: 0.0872 - val_loss: 10.6032
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6588 - loss: 1.5553 - val_accuracy: 0.0864 - val_loss: 10.6564
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6607 - loss: 1.5367 - val_accuracy: 0.0855 - val_loss: 10.6791
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6659 - loss: 1.5196 - val_accuracy: 0.0833 - val_loss: 10.7338
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6678 - loss: 1.5043 - val_accuracy: 0.0856 - val_loss: 10.7901
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6720 - loss: 1.4859 - val_accuracy: 0.0843 - val_loss: 10.8412
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 60ms/step - accuracy: 0.6763 - loss: 1.4679 - val_accuracy: 0.0838 - val_loss: 10.8955
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.6797 - loss: 1.4537 - val_accuracy: 0.0837 - val_loss: 10.9287
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 59ms/step - accuracy: 0.6831 - loss: 1.4356 - val_accuracy: 0.0840 - val_loss: 10.9918
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 60ms/step - accuracy: 0.6867 - loss: 1.4185 - val_accuracy: 0.0837 - val_loss: 11.0341
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.6897 - loss: 1.4042 - val_accuracy: 0.0830 - val_loss: 11.0945
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 59ms/step - accuracy: 0.6937 - loss: 1.3889 - val_accuracy: 0.0823 - val_loss: 11.1427
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 61ms/step - accuracy: 0.6973 - loss: 1.3727 - val_accuracy: 0.0838 - val_loss: 11.1861
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6996 - loss: 1.3615 - val_accuracy: 0.0829 - val_loss: 11.2397
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.7016 - loss: 1.3463 - val_accuracy: 0.0838 - val_loss: 11.2705
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.7062 - loss: 1.3302 - val_accuracy: 0.0817 - val_loss: 11.3233
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.7088 - loss: 1.3169 - val_accuracy: 0.0826 - val_loss: 11.3677
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.7117 - loss: 1.3024 - val_accuracy: 0.0828 - val_loss: 11.4111
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.7150 - loss: 1.2900 - val_accuracy: 0.0802 - val_loss: 11.4684
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.7167 - loss: 1.2756 - val_accuracy: 0.0801 - val_loss: 11.5128
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.7216 - loss: 1.2617 - val_accuracy: 0.0803 - val_loss: 11.5438
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 60ms/step - accuracy: 0.7220 - loss: 1.2513 - val_accuracy: 0.0810 - val_loss: 11.5979
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.7260 - loss: 1.2379 - val_accuracy: 0.0807 - val_loss: 11.6438
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.7286 - loss: 1.2246 - val_accuracy: 0.0811 - val_loss: 11.6872
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 59ms/step - accuracy: 0.7318 - loss: 1.2134 - val_accuracy: 0.0808 - val_loss: 11.7375

In [36]:
#used to load a model from outside
#from tensorflow.keras.models import load_model

#lstm_model = load_model("lstm_model.h5")

In [37]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [38]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [39]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [40]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [41]:
seed_text = "what are you"
next_word = predictor(lstm_model,tokinizer,seed_text,max_len)
print(next_word)

worrying

In [42]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [43]:
seed = "are you a "
generate_text = generate_text(lstm_model,tokinizer,seed,max_len,10)
print(generate_text)

are you a  part of you not your way so they will be

In [44]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokinizer, f)

In [45]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)