**PIVOT TABLE**

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    440     39   John  January      Q1
1  2023-01-02       B   West    687     94   Mary  January      Q1
2  2023-01-03       C  North    327     46    Bob  January      Q1
3  2023-01-04       D  South    993     31  Alice  January      Q1
4  2023-01-05       A   East    257     68   John  January      Q1
5  2023-01-06       B   West    222     56   Mary  January      Q1
6  2023-01-07       C  North    994     24    Bob  January      Q1
7  2023-01-08       D  South    854     75  Alice  January      Q1
8  2023-01-09       A   East    715     20   John  January      Q1
9  2023-01-10       B   West    321     25   Mary  January      Q1
10 2023-01-11       C  North    308     68    Bob  January      Q1
11 2023-01-12       D  South    414     87  Alice  January      Q1
12 2023-01-13       A   East    896     98   John  January      Q1
13 2023-01-14       B   West    872     59   Mary  January      Q1
14 2023-01-15       C  North    713     40    Bob  January      Q1
15 2023-01-16       D  South    747     53  Alice  January      Q1
16 2023-01-17       A   East    229     22   John  January      Q1
17 2023-01-18       B   West    126     59   Mary  January      Q1
18 2023-01-19       C  North    250     19    Bob  January      Q1
19 2023-01-20       D  South    945     25  Alice  January      Q1

In [4]:
pd.pivot_table(df, values ='Sales', index = 'Region' , columns=  'Product')

Product      A      B      C      D
Region
East     507.4    NaN    NaN    NaN
North      NaN    NaN  518.4    NaN
South      NaN    NaN    NaN  790.6
West       NaN  445.6    NaN    NaN

In [6]:
pd.pivot_table(df, values ='Sales', index = 'Region' , columns=  'Product',  aggfunc= 'median')

Product      A      B      C      D
Region
East     440.0    NaN    NaN    NaN
North      NaN    NaN  327.0    NaN
South      NaN    NaN    NaN  854.0
West       NaN  321.0    NaN    NaN

In [8]:
pivot2= pd.pivot_table(df, values =['Sales','Units'], index = 'Region' , columns=  'Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     507.4    NaN    NaN    NaN  49.4   NaN   NaN   NaN
North      NaN    NaN  518.4    NaN   NaN   NaN  39.4   NaN
South      NaN    NaN    NaN  790.6   NaN   NaN   NaN  54.2
West       NaN  445.6    NaN    NaN   NaN  58.6   NaN   NaN

**Cross Tabs**

In [10]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

**OPERATIONS**

In [12]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [13]:
df1.shape

(5, 3)

In [14]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [15]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [16]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [17]:
df1['A'] +10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [18]:
def square(x):
    return x**2

In [19]:
df1['B'] = df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [20]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500